# Generated by Django 3.2.5 on 2021-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
