# Generated by Django 3.2.5 on 2021-08-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_email_address',
            field=models.EmailField(default='not_given', max_length=254),
        ),
    ]
