# Generated by Django 3.2.5 on 2021-08-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_address',
            field=models.EmailField(default='not_given', max_length=254),
        ),
    ]
