# Generated by Django 3.2.5 on 2021-08-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=2.99, editable=False, max_digits=3),
        ),
    ]
