# Generated by Django 3.2.5 on 2021-09-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210824_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
