# Generated by Django 3.2.5 on 2021-09-28 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import items.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('surname', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='Special Offer', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, default=items.utils.create_new_sku, max_length=10, null=True)),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('set_sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('final_price', models.DecimalField(decimal_places=2, editable=False, max_digits=6, null=True)),
                ('quantity_sold', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('featured', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('active', models.BooleanField(default=True)),
                ('age_range', models.ManyToManyField(to='items.Age_range')),
                ('author', models.ManyToManyField(blank=True, to='items.Author')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.campaign')),
                ('genre', models.ManyToManyField(blank=True, to='items.Genre')),
            ],
        ),
    ]
