# Generated by Django 3.2.5 on 2021-08-13 20:22

from django.db import migrations, models
import items.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('surname', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('screen_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, default=items.utils.create_new_sku, max_length=10, null=True)),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('quantity_sold', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('set_sale_price', models.DecimalField(decimal_places=2, max_digits=6, null=True, blank=True)),
                ('age_range', models.ManyToManyField(to='items.Age_range')),
                ('author', models.ManyToManyField(to='items.Author')),
                ('genre', models.ManyToManyField(to='items.Genre')),
            ],
        ),
    ]
