# Generated by Django 3.2.5 on 2021-07-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='reading_age',
        ),
        migrations.DeleteModel(
            name='Reading_age',
        ),
        migrations.AddField(
            model_name='item',
            name='age_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.age_range'),
        ),
    ]
