# Generated by Django 3.2.5 on 2021-08-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='final_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6, null=True),
        ),
    ]
