# Generated by Django 3.2.5 on 2021-09-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.ManyToManyField(blank=True, to='items.Author'),
        ),
        migrations.AlterField(
            model_name='item',
            name='genre',
            field=models.ManyToManyField(blank=True, to='items.Genre'),
        ),
    ]
