# Generated by Django 3.2.5 on 2021-07-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20210720_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_sold',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
