# Generated by Django 3.2.5 on 2021-07-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_quantity_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
