# Generated by Django 3.2.5 on 2021-09-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20210915_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_deleted',
        ),
    ]
