# Generated by Django 3.2.5 on 2021-07-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20210726_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='set_sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
