# Generated by Django 3.2.5 on 2021-09-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20210916_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='original_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
