# Generated by Django 3.2.5 on 2021-09-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_item_original_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='Special Offer', max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('multibuy', models.BooleanField(default=False)),
                ('included_items', models.ManyToManyField(to='items.Item')),
            ],
        ),
    ]
