# Generated by Django 3.2.5 on 2021-08-12 11:28

from django.db import migrations, models
import items.utils


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_item_set_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, default=items.utils.create_new_sku, max_length=10, null=True),
        ),
    ]
