# Generated by Django 3.2.5 on 2021-09-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='multibuy',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
