# Generated by Django 3.2.5 on 2021-09-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20210922_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='description',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='display_collection_only',
        ),
    ]
