# Generated by Django 3.2.5 on 2021-09-23 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20210922_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='included_items',
        ),
        migrations.AddField(
            model_name='item',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.campaign'),
        ),
    ]
