# Generated by Django 3.2.5 on 2021-09-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_item_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='original_sale_price',
        ),
    ]
